name: Keyra
description: "A Flutter app for AI-generated children's books"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  timeago: ^3.6.0
  uuid: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^13.0.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  logger: ^2.0.2+1
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.3
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  google_sign_in: ^6.2.1
  hugeicons: ^0.0.7
  audioplayers: ^5.2.1
  rxdart: ^0.27.7
  japanese_word_tokenizer: ^0.0.3
  ruby_text: ^3.0.3
  xml: ^6.3.0
  sqflite: ^2.3.0
  archive: ^3.4.9
  flutter_dotenv: ^5.1.0
  lottie: 2.7.0
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  bloc_test: ^9.1.5
  mockito: ^5.4.3
  path: ^1.8.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/onboarding/
    - assets/fonts/
    - assets/flags/
    - assets/loader/
    - assets/audio/
    - assets/audio/books/
    - assets/audio/books/magic_forest/
    - assets/audio/books/magic_forest/de/
    - assets/audio/books/magic_forest/en/
    - assets/audio/books/magic_forest/es/
    - assets/audio/books/magic_forest/fr/
    - assets/audio/books/magic_forest/it/

  fonts:
    - family: FascinateInline
      fonts:
        - asset: assets/fonts/FascinateInline-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: FascinateInline
      fonts:
        - asset: assets/fonts/FascinateInline-Regular.ttf
