// ignore_for_file: constant_identifier_names

import 'badge_level.dart';
import 'badge_requirements.dart';

/// Configuration map for badge requirements.
/// This makes it easy to modify requirements for existing badges
/// or add new ones when badge levels are expanded.
const badgeRequirementsConfig = {
  BadgeLevel.beginner: BadgeRequirements(
    level: BadgeLevel.beginner,
    displayName: 'badge_beginner',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 20,
    requiredFavoriteBooks: 10,
    requiredReadingStreak: 15,
  ),
  BadgeLevel.intermediate: BadgeRequirements(
    level: BadgeLevel.intermediate,
    displayName: 'badge_intermediate',
    assetPath: 'assets/badge/open-book.png',
    requiredBooksRead: 40,
    requiredFavoriteBooks: 18,
    requiredReadingStreak: 25,
  ),
  BadgeLevel.advanced: BadgeRequirements(
    level: BadgeLevel.advanced,
    displayName: 'badge_advanced',
    assetPath: 'assets/badge/medal.png',
    requiredBooksRead: 50,
    requiredFavoriteBooks: 20,
    requiredReadingStreak: 30,
  ),
  BadgeLevel.master: BadgeRequirements(
    level: BadgeLevel.master,
    displayName: 'badge_master',
    assetPath: 'assets/badge/wizard-hat.png',
    requiredBooksRead: 75,
    requiredFavoriteBooks: 25,
    requiredReadingStreak: 40,
  ),
  BadgeLevel.explorer: BadgeRequirements(
    level: BadgeLevel.explorer,
    displayName: 'badge_explorer',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 100,
    requiredFavoriteBooks: 30,
    requiredReadingStreak: 50,
  ),
  BadgeLevel.voyager: BadgeRequirements(
    level: BadgeLevel.voyager,
    displayName: 'badge_voyager',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 150,
    requiredFavoriteBooks: 35,
    requiredReadingStreak: 60,
  ),
  BadgeLevel.weaver: BadgeRequirements(
    level: BadgeLevel.weaver,
    displayName: 'badge_weaver',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 200,
    requiredFavoriteBooks: 40,
    requiredReadingStreak: 75,
  ),
  BadgeLevel.navigator: BadgeRequirements(
    level: BadgeLevel.navigator,
    displayName: 'badge_navigator',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 250,
    requiredFavoriteBooks: 45,
    requiredReadingStreak: 90,
  ),
  BadgeLevel.pioneer: BadgeRequirements(
    level: BadgeLevel.pioneer,
    displayName: 'badge_pioneer',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 300,
    requiredFavoriteBooks: 50,
    requiredReadingStreak: 100,
  ),
  BadgeLevel.royalty: BadgeRequirements(
    level: BadgeLevel.royalty,
    displayName: 'badge_royalty',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 400,
    requiredFavoriteBooks: 60,
    requiredReadingStreak: 120,
  ),
  BadgeLevel.baron: BadgeRequirements(
    level: BadgeLevel.baron,
    displayName: 'badge_baron',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 500,
    requiredFavoriteBooks: 70,
    requiredReadingStreak: 150,
  ),
  BadgeLevel.legend: BadgeRequirements(
    level: BadgeLevel.legend,
    displayName: 'badge_legend',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 600,
    requiredFavoriteBooks: 80,
    requiredReadingStreak: 180,
  ),
  BadgeLevel.wizard: BadgeRequirements(
    level: BadgeLevel.wizard,
    displayName: 'badge_wizard',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 700,
    requiredFavoriteBooks: 90,
    requiredReadingStreak: 200,
  ),
  BadgeLevel.epic: BadgeRequirements(
    level: BadgeLevel.epic,
    displayName: 'badge_epic',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 800,
    requiredFavoriteBooks: 100,
    requiredReadingStreak: 225,
  ),
  BadgeLevel.titan: BadgeRequirements(
    level: BadgeLevel.titan,
    displayName: 'badge_titan',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 900,
    requiredFavoriteBooks: 110,
    requiredReadingStreak: 250,
  ),
  BadgeLevel.sovereign: BadgeRequirements(
    level: BadgeLevel.sovereign,
    displayName: 'badge_sovereign',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 1000,
    requiredFavoriteBooks: 120,
    requiredReadingStreak: 275,
  ),
  BadgeLevel.virtuoso: BadgeRequirements(
    level: BadgeLevel.virtuoso,
    displayName: 'badge_virtuoso',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 1200,
    requiredFavoriteBooks: 140,
    requiredReadingStreak: 300,
  ),
  BadgeLevel.luminary: BadgeRequirements(
    level: BadgeLevel.luminary,
    displayName: 'badge_luminary',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 1400,
    requiredFavoriteBooks: 160,
    requiredReadingStreak: 325,
  ),
  BadgeLevel.beacon: BadgeRequirements(
    level: BadgeLevel.beacon,
    displayName: 'badge_beacon',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 1600,
    requiredFavoriteBooks: 180,
    requiredReadingStreak: 350,
  ),
  BadgeLevel.radiant: BadgeRequirements(
    level: BadgeLevel.radiant,
    displayName: 'badge_radiant',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 1800,
    requiredFavoriteBooks: 200,
    requiredReadingStreak: 375,
  ),
  BadgeLevel.lighthouse: BadgeRequirements(
    level: BadgeLevel.lighthouse,
    displayName: 'badge_lighthouse',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 2000,
    requiredFavoriteBooks: 220,
    requiredReadingStreak: 400,
  ),
  BadgeLevel.infinite: BadgeRequirements(
    level: BadgeLevel.infinite,
    displayName: 'badge_infinite',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 2500,
    requiredFavoriteBooks: 250,
    requiredReadingStreak: 450,
  ),
  BadgeLevel.renaissance: BadgeRequirements(
    level: BadgeLevel.renaissance,
    displayName: 'badge_renaissance',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 3000,
    requiredFavoriteBooks: 300,
    requiredReadingStreak: 500,
  ),
  BadgeLevel.ultimate: BadgeRequirements(
    level: BadgeLevel.ultimate,
    displayName: 'badge_ultimate',
    assetPath: 'assets/badge/caterpillar.png',
    requiredBooksRead: 5000,
    requiredFavoriteBooks: 500,
    requiredReadingStreak: 750,
  ),
};
