// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMYhNLdv3wlJx4q6pY1D8GzH6xTjhB810',
    appId: '1:683024343520:web:29f7f1414c6008e36acb85',
    messagingSenderId: '683024343520',
    projectId: 'keyra-93667',
    authDomain: 'keyra-93667.firebaseapp.com',
    storageBucket: 'keyra-93667.firebasestorage.app',
    measurementId: 'G-TR5Q3Q2B2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkfZqYt2_tss0_kjJf5yVH-QbRrZX-HYg',
    appId: '1:683024343520:android:75f549c3744c8df16acb85',
    messagingSenderId: '683024343520',
    projectId: 'keyra-93667',
    storageBucket: 'keyra-93667.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8FUu9PufTYzGW2OZ9w_gW13HcTZ2EHI',
    appId: '1:683024343520:ios:a1468ec731f3a8fa6acb85',
    messagingSenderId: '683024343520',
    projectId: 'keyra-93667',
    storageBucket: 'keyra-93667.firebasestorage.app',
    androidClientId: '683024343520-4u8fgl4eiq2n3knc7m3r5ctujc8c1pe9.apps.googleusercontent.com',
    iosClientId: '683024343520-n2q59bm55nes70atb4bvhu719qci94d5.apps.googleusercontent.com',
    iosBundleId: 'com.keyra.app',
  );

}